log:
  #debug, info, warn, error
  level: debug
  format: '%{color}%{time:2006-01-02 15:04:05.000 MST} %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
db:
  server: root:aisino@tcp(192.168.20.11:3306)/zone?charset=utf8&parseTime=True&loc=Local
port:
  port: 8000
